services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URL=mysql://donaninita-user:donaninita-password@db:3306/donaninita-database
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: donaninita-password
      MYSQL_DATABASE: donaninita-database
      MYSQL_USER: donaninita-user
      MYSQL_PASSWORD: donaninita-password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
